pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: printenv
  displayName: Print Environment
- script: |
    sudo apt-get update 
    sudo apt-get install -y build-essential libssl-dev uuid-dev \
        libgpgme11-dev squashfs-tools libseccomp-dev wget \
        pkg-config git
  displayName: Install system dependencies for Singularity
- script: |
    export VERSION=3.4.1
    wget --quiet https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz
    tar -xzf singularity-${VERSION}.tar.gz
    cd singularity
    ./mconfig
    make -C builddir
    sudo make -C builddir install
    cd ..
    singularity --version
  displayName: Compile and install Singularity
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH
- bash: sudo chown -R $USER /usr/share/miniconda
  displayName: Take ownership of Conda installation
- script: java -version
  displayName: Java version
- script: |
    conda config --add channels defaults
    conda config --add channels bioconda
    conda config --add channels conda-forge
  displayName: Configure Conda channels
- script: |
    conda install conda=4.7.12 -y
  displayName: Update Conda
- script: |
    conda install nextflow sra-tools -y
  displayName: Install Nextflow and NCBI SRA Tools
- script: |
    nextflow run main.nf --help
  displayName: Print help message for workflow
- script: |
    mkdir -p reads/original
    cd reads/original
    echo "Download paired end Illumina reads for ERR3338653"
    fasterq-dump ERR3338653
    cd ..
    cat original/ERR3338653_1.fastq | perl -pe 's/^@([\w\.]+) (\S+) (\S+)/@\2 1:N:0:51/' > ERR3338653_1.fastq
    cat original/ERR3338653_2.fastq | perl -pe 's/^@([\w\.]+) (\S+) (\S+)/@\2 2:N:0:51/' > ERR3338653_2.fastq
    echo "Fixed FASTQ headers in ERR3338653 for IRMA"
    cd ..
    nextflow run peterk87/nf-iav-illumina --reads "reads/*_{1,2}.fastq" --outdir results
    wc -l results/consensus/*/*.fa
  displayName: Run workflow on test data from NCBI SRA
