pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: printenv
  displayName: Print Environment
- script: |
    wget -O- http://neuro.debian.net/lists/xenial.us-ca.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
    sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
    sudo apt-get update 
    sudo apt-get install -y build-essential singularity-container wget
  displayName: Install system dependencies and Singularity
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH
- bash: sudo chown -R $USER /usr/share/miniconda
  displayName: Take ownership of Conda installation
- script: java -version
  displayName: Java version
- script: |
    conda config --add channels defaults
    conda config --add channels bioconda
    conda config --add channels conda-forge
  displayName: Configure Conda channels
- script: |
    conda install conda=4.7.12 nextflow sra-tools -y
  displayName: Update Conda and Install Nextflow and NCBI SRA Tool
- script: |
    nextflow run main.nf --help
  displayName: Print help message for workflow
- script: |
    mkdir -p reads/original
    cd reads/original
    echo "Download paired end Illumina reads for ERR3338653"
    fasterq-dump ERR3338653
    cd ..
    cat original/ERR3338653_1.fastq | perl -pe 's/^@([\w\.]+) (\S+) (\S+)/@\2 1:N:0:51/' > ERR3338653_1.fastq
    cat original/ERR3338653_2.fastq | perl -pe 's/^@([\w\.]+) (\S+) (\S+)/@\2 2:N:0:51/' > ERR3338653_2.fastq
    echo "Fixed FASTQ headers in ERR3338653 for IRMA"
    cd ..
    nextflow run peterk87/nf-iav-illumina \
      --reads "reads/*_{1,2}.fastq" \
      --outdir results \
      --max_cpus 2
    wc -l results/consensus/*/*.fa
  displayName: Run workflow on test data from NCBI SRA
