name: nf-iav-illumina-1.1.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - blast=2.9.0
  - python=3.7.3
  - pip=19.2.3
  - pip:
    - click
    - numpy
    - pandas
    - xlsxwriter
